### ISSUE TITLE
I found an error of "The pseudocode of minimum distance label implementation of MLC."

### ISSUE THREAD

**Issue by cpp-apprentice** [jdlph/shortest-path-algorithms#1]
![image](https://user-images.githubusercontent.com/54906999/115136928-948f0f80-a055-11eb-8c94-645c10a3d807.png)
As you can see, the 8-th row of the pseudocode says: remove i with the minimum distance label from LIST. However, it should be: remove i with the minimum distance label from N-LIST. Thank you.

**Comment by jdlph** [comment]
What's N-LIST?

**Comment by cpp-apprentice** [comment]
N : set of nodes 
N - LIST means the set of nodes which is in N and not in LIST.

**Comment by jdlph** [comment]
Why do we need it here? If we include it here, shall we modify the other parts too?

**Comment by cpp-apprentice** [comment]
My fault. I have checked the Network Flow written by Ahuja again. It is that I did not understand the pseudocode correctly. Sorry.

**Comment by jdlph** [comment]
No worries. I guess you were talking about the raw implementation of Dijkstra's algorithm, which is equivalent but not the same to this one under the MLC implementation. This implementation itself is only briefly mentioned in Network Flows without pseudo code as its advanced form, i.e., the heap implementation, is usually adopted for the superior performance. 

I will close the issue here. Thank you for taking your time to look into the project! Please let me know if you have any other questions or feedback by opening a new ticket.
